---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pg
resources:
  - ../base
patches:
  - path: postgres-vc-patch.yaml
configMapGenerator:
  - name: postgres-init
    files:
      - 01-initdb.sql
secretGenerator:
  - name: postgres-secrets
    envs:
      - secrets.env
