---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  serviceName: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
    spec:
      containers:
        - name: postgresql
          image: docker.io/library/postgres:15-alpine
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: var
              mountPath: /var/run/postgresql
      volumes:
        - name: init-volume
          configMap:
            name: postgres-init
            optional: true
        - name: var
          emptyDir:
            sizeLimit: 100Mi
